### ISSUE TITLE
Replace python 3 de-  & re-install with explicit creation of symlink

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/Taskwarrior-installation#58]
In folder `AutoInstallTaskwarrior`, file `TaskwarriorInstaller.ps1` the lines:

```
"Step E7"
bash -c "echo 'yes' | sudo apt-get remove python3-apt"
"Step E7.0.1"
bash -c "echo 'yes' | sudo apt-get install python3-apt"
"Step E7.0.2"
```

Are included to prevent error:
```
Please enter:sudo python3 /home/testlinuxname/maintenance/taskw_gcal_sync/tw_gcal_sync -c "TW Reminders" -t remindme
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 27, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>1

    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 27, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
```
According to the comment by Gibbsoft, the error can somehow be releated to a symlink. Vague in memory I recall when I initially tried to manually install/use taskw_gcal_sync, there was an identical issue with symlink, where I thought it meant some reference to some file/library was not created in some version of either Ubuntu or Python (before I arrived at this error: https://github.com/bergercookie/taskw_gcal_sync/issues/7).

Perhaps you can resolve the `apt_pkg` error with a single quick command (that fixes a symlink if that's possible), instead of by first uninstalling, and then reinstalling python 3.

If you are hence able to replace the above 2 commands with a single command tthat is executed fast, you might be able to reduce the installation time by another minute/a few minutes.

**Comment by a-t-0** [comment]
Perhaps incorporate ppas:
https://blog.smallsec.ca/2017/09/07/installing-python3-6-on-wsl/

**Comment by a-t-0** [comment]
The python 3 de- & re-installation has been removed.
